-- Este archivo no crea cuentas por diseño.
--
-- Las versiones anteriores insertaban usuarios con una contraseña conocida y
-- hashes que no correspondían a esa contraseña, por lo que no servían ni como
-- datos de desarrollo ni como recuperación administrativa.
--
-- Ejecuta primero las migraciones canónicas de `supabase/migrations/` y usa
-- `scripts/bootstrap-admin.mjs` con credenciales entregadas en variables de
-- entorno. El script no expone un endpoint y no contiene valores por defecto.
